packages:
  - apps/*
  - packages/*
  - configs/*

catalog:
  '@changesets/cli': ^2.29.7
  '@commitlint/cli': ^20.1.0
  '@commitlint/config-conventional': ^20.0.0
  '@eslint/js': ^9.39.1
  '@types/node': ^22.15.3
  eslint: ^9.39.1
  husky: ^9.1.7
  lint-staged: ^16.2.7
  prettier: ^3.7.4
  tsup: ^8.5.1
  turbo: ^2.7.5
  typescript: 5.9.2

catalogs:
  eslint-plugins:
    '@next/eslint-plugin-next': ^15.1.0
    '@react-native/eslint-config': ^0.82.1
    eslint-config-prettier: ^10.1.1
    eslint-plugin-only-warn: ^1.1.0
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-native: ^5.0.0
    eslint-plugin-storybook: ^10.0.8
    eslint-plugin-turbo: ^2.6.0
    globals: ^16.5.0
    typescript-eslint: ^8.46.3
  logger-libs:
    pino: ^9.9.4
    pino-http: ^10.3.0
    pino-pretty: ^13.1.1
  nextjs:
    next: ^16.1.0
  prettier-plugins:
    '@trivago/prettier-plugin-sort-imports': ^6.0.0
  radix-ui:
    '@radix-ui/react-slot': 1.2.4
  react19:
    '@types/react': ^19.1.0
    '@types/react-dom': ^19.1.0
    react: 19.2.3
    react-dom: 19.2.3
  storybook:
    '@storybook/addon-a11y': 8.6.15
    '@storybook/addon-essentials': 8.6.15
    '@storybook/blocks': 8.6.15
    '@storybook/react': 8.6.15
    '@storybook/react-vite': 8.6.15
    storybook: 8.6.15
  testing:
    '@testing-library/jest-dom': ^6.9.1
    '@testing-library/react': ^16.0.0
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    jsdom: ^27.0.0
    vitest: ^3.2.4
  vite-ecosystem:
    '@vitejs/plugin-react': ^5.0.4
    vite: ^6.4.1
    vite-tsconfig-paths: ^6.0.2
  web-ui:
    '@tailwindcss/postcss': ^4.1.16
    class-variance-authority: 0.7.1
    clsx: ^2.1.1
    lucide-react: ^0.561.0
    postcss: ^8.5.6
    tailwind-merge: ^3.4.0
    tailwindcss: ^4.0.0

linkWorkspacePackages: true
